# ----------------- Start of Corrected config.yml -----------------
### LLM settings ###
models:
  default_chat_model:
    type: chat
    model_provider: groq
    auth_type: api_key
    api_key: ${GROQ_API_KEY}
    model: llama-3.3-70b-versatile
    model_supports_json: true
    concurrent_requests: 25
    async_mode: threaded
    retry_strategy: native
    max_retries: 5
    tokens_per_minute: null
    requests_per_minute: null

  default_embedding_model:
    type: embedding
    model_provider: ollama
    auth_type: api_key
    api_key: DUMMY_KEY_FOR_OLLAMA_BYPASS
    model: nomic-embed-text
    api_base: http://localhost:11434
    model_supports_json: true
    concurrent_requests: 25
    async_mode: threaded
    retry_strategy: native
    max_retries: 10
    tokens_per_minute: null
    requests_per_minute: null

### Input settings ###
input:
  type: file
  file_type: csv
  base_dir: "data"
  file_pattern: "test.csv" #"processed_incidents.csv"
  text_column: "document_text"

chunks:
  size: 1200
  overlap: 100
  # group_by_columns: [id]

### Output/storage settings ###
output:
  type: file
  base_dir: "output"

cache:
  type: file
  base_dir: "cache"

reporting:
  type: file
  base_dir: "logs"

vector_store:
  default_vector_store:
    type: lancedb
    db_uri: "output/lancedb" # This path is relative to your project root
    container_name: default
    overwrite: True

### Workflow settings ###
embed_text:
  model_id: default_embedding_model
  vector_store_id: default_vector_store

extract_graph:
  model_id: default_chat_model
  prompt: "prompts/entity_extraction.txt"
  entity_types:
    - INCIDENT_TYPE
    - INJURY_TYPE
    - BODY_PART
    - SEVERITY_LEVEL
    - ORGANIZATION
    - WORKPLACE
    - WORK_PROCESS
    - DESCRIPTION_SUMMARY
  max_gleanings: 1

summarize_descriptions:
  model_id: default_chat_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english
  async_mode: threaded

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false
  model_id: default_chat_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  model_id: default_chat_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

embed_graph:
  enabled: false

umap:
  enabled: false

snapshots:
  graphml: false
  embeddings: false

### Query settings ###
local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  chat_model_id: default_chat_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"

basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
